#!/usr/bin/env bash
#installing nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > sudo tee -a /var/www/html/index.nginx-debian.html
sudo service nginx start
