#!/usr/bin/env bash
#configure web-02 to be identical to web-01.

FILE="/etc/nginx/sites-available/default"
ERRORFILE="/var/www/html/404.html"

REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}\n"
ERRORREDIRECT="\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
CUSTOMHEADER='\n\tadd_header X-Served-By $hostname;\n'

STRING="Hello World!"
FOUR="Ceci n'est pas une page"

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
bash -c "echo '$STRING' > /var/www/html/index.nginx-debian.html"
sed -i "37i\ $REDIRECT" "$FILE"

bash -c "echo '$FOUR' > '$ERRORFILE'"
sed -i "37i\ $ERRORREDIRECT" "$FILE"

sed -i "37i\ $CUSTOMHEADER" "$FILE"
service nginx restart

echo "Nginx has been configured with a custom X-Served-By $CUSTOMHEADER"
