#!/usr/bin/env bash
#checking if a file exists

file="school"

if [ -e $file ]
then
	echo "school file exists"
		
		if [ ! -s $file ]
		then
			echo "school file is empty"
		else 
			echo "school file is not empty"
				if [ -f $file ]
                		then
                        		echo "school file is a regular file"
                		fi
		fi
		
else
	echo "school file does not exist"
fi
