#!/usr/bin/env bash
#checking if a file exists

school="school"

if [ -e $school ]
then
	echo "school file exists"
		
		if [ -s $school ]
		then
			echo "school file is empty"
		else 
			echo "school file is not empty"
				if [ -f $school ]
                		then
                        		echo "school file is a regular file"
                		fi
		fi
		
else
	echo "school file does not exist"
fi
